POST localhost:8080/api/v1/members
Content-Type: application/json

{
  "name": "사나마"
}

###

GET localhost:8080/api/v1/members?page=0&searchSorting=JOIN
Content-Type: application/json

###

PUT localhost:8080/api/v1/members/6/inquiry
Content-Type: application/json
